export const config = {
  MAX_HAND_SIZE: 6,
  MAX_GOLD: 8,
  GOLD_PER_TURN: 2,
  PLAYER_1_STARTING_GOLD: 2,
  PLAYER_2_STARTING_GOLD: 3,
  GENERAL_DEFAULT_ATTACK: 2,
  GENERAL_DEFAULT_HP: 25,
  GENERAL_DEFAULT_SPEED: 3
} as const;
