export const config = {
  VERSION: '0.2.2',
  MAX_COPIES_PER_CARD: 3,
  MAX_DECK_SIZE: 20,
  MAX_HAND_SIZE: 6,
  MAX_GOLD: 8,
  GOLD_PER_TURN: 3,
  PLAYER_1_STARTING_GOLD: 2,
  PLAYER_2_STARTING_GOLD: 3,
  GENERAL_DEFAULT_ATTACK: 2,
  GENERAL_DEFAULT_HP: 25,
  GENERAL_DEFAULT_SPEED: 3,
  STARTING_HAND_SIZE: 3,
  CARD_DRAW_PER_TURN: 1
} as const;
