/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.13.2.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as analytics from "../analytics.js";
import type * as auth from "../auth.js";
import type * as collection from "../collection.js";
import type * as featureFlags from "../featureFlags.js";
import type * as formats from "../formats.js";
import type * as friends from "../friends.js";
import type * as games from "../games.js";
import type * as hathora from "../hathora.js";
import type * as loadout from "../loadout.js";
import type * as lobbies from "../lobbies.js";
import type * as matchmaking from "../matchmaking.js";
import type * as users from "../users.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  analytics: typeof analytics;
  auth: typeof auth;
  collection: typeof collection;
  featureFlags: typeof featureFlags;
  formats: typeof formats;
  friends: typeof friends;
  games: typeof games;
  hathora: typeof hathora;
  loadout: typeof loadout;
  lobbies: typeof lobbies;
  matchmaking: typeof matchmaking;
  users: typeof users;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
