import { getCurrentGameUsecase } from './game/usecases/get-current-game.usecase';
import { startGameUsecase } from './game/usecases/start-game.usecase';
import { timeoutGameUsecase } from './game/usecases/timeout-game.usecase';
import { finishGameUsecase } from './game/usecases/finish-game.usecase';
import { internalCancelGameUsecase } from './game/usecases/internal-cancel-game.usecase';
import { cancelGameUsecase } from './game/usecases/cancel-game.usecase';
import { endGameUsecase } from './game/usecases/end-game.usecase';
import { getGameUsecase } from './game/usecases/get-game.usercase';
import { getAllOngoingGamesUsecase } from './game/usecases/get-all-ongoing-games';
import { getMyGameHistoryUsecase } from './game/usecases/get-my-game-history.usecase';
import { getLatestGamesWithReplaysUsecase } from './game/usecases/get-latest-games-with-replays.usecase';
import { createGameReplayUsecase } from './game/usecases/create-game-replay.usecase';
import { getGameReplayUsecase } from './game/usecases/get-game-replay.usecase';

export const getCurrent = getCurrentGameUsecase;
export const start = startGameUsecase;
export const timeout = timeoutGameUsecase;
export const finish = finishGameUsecase;
export const internalCancel = internalCancelGameUsecase;
export const cancel = cancelGameUsecase;
export const end = endGameUsecase;
export const getById = getGameUsecase;
export const getAllOngoing = getAllOngoingGamesUsecase;
export const myGameHistory = getMyGameHistoryUsecase;
export const latestGamesWithReplays = getLatestGamesWithReplaysUsecase;
export const creatReplay = createGameReplayUsecase;
export const replayByGameId = getGameReplayUsecase;
